kind: ServiceAccount
apiVersion: v1
metadata:
  name: datadog-agent
  namespace: django-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datadog-agent
rules:
- apiGroups:
  - ""
  resources:
  - services
  - events
  - endpoints
  - pods
  - nodes
  - componentstatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - datadogtoken             # Kubernetes event collection state
  - datadog-leader-election  # Leader election token
  verbs:
  - get
  - update
- apiGroups:  # To create the leader election token
  - ""
  resources:
  - configmaps
  verbs:
  - create
- nonResourceURLs:
  - "/version"
  - "/healthz"
  verbs:
  - get
- apiGroups:  # Kubelet connectivity
  - ""
  resources:
  - nodes/metrics
  - nodes/spec
  - nodes/proxy
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog-agent
subjects:
- kind: ServiceAccount
  name: datadog-agent
  namespace: django-example
---
#
# This SCC is required to enable the full featureset of the
# Datadog Agent. The kubelet-only variant can run with the
# default restricted SCC
#
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: datadog-agent
users:
- system:serviceaccount:django-example:datadog-agent
priority: 10
# Allow host ports for dsd / trace / logs intake
allowHostPorts: true
# Allow host PID for dogstatsd origin detection
allowHostPID: true
# Allow hostPath for docker / process metrics
volumes:
- configMap
- downwardAPI
- emptyDir
- hostPath
- secret
# Use the `spc_t` selinux type to access the
# docker socket + proc and cgroup stats
seLinuxContext:
  type: MustRunAs
  seLinuxOptions:
    user: "system_u"
    role: "system_r"
    type: "spc_t"
    level: "s0"
#
# The rest is copied from 3.7.0 restricted SCC
#
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowPrivilegedContainer: false
allowedFlexVolumes: []
defaultAddCapabilities: []
readOnlyRootFilesystem: false
runAsUser:
  type: MustRunAsRange
fsGroup:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
seccompProfiles: []
requiredDropCapabilities: []
allowedCapabilities: []

